version: "3.3"

services:
  postgis:
    image: postgis/postgis
    container_name: geoserver_postgis
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - dbGeoSeverVolume:/var/lib/postgresql/data/
    networks: 
      - geoServerNetwork
    environment: 
      POSTGRES_PASSWORD: ${PSQL_PSW}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_DB: ${PSQL_DB}

  geoserver:
    build: ./geoserver
    container_name: geoserver
    restart: always
    ports: 
      - 8080:8080
    volumes: 
      - ./geoserver/app:/usr/share/geoserver
    networks: 
      - geoServerNetwork

  geoserver_281:
    build: ./geoserver_281
    container_name: geoserver_281
    restart: always
    ports:
      - 8081:8080
    volumes:
      - ./geoserver_281/app:/usr/share/geoserver
    networks: 
      - geoServerNetwork


volumes:
  dbGeoSeverVolume:
  geoserver_data_dir:

networks:
  geoServerNetwork:
    driver: "bridge"
